### ISSUE TITLE
[1.11.2] Server start-up crash using 2.0.0a4

### ISSUE THREAD

**Issue by ruyanve** [elytra/Correlated#59] opened 2017-04-22 08:47 UTC
Forge:  13.20.0.2282
Log: https://gist.github.com/ruyanve/0d55a5fed1280810d5f74126904388a2

Cheers guys, looking forward to see this mod develop!

**Comment by darkevilmac** [comment] 2017-04-22 09:31
@unascribed Time saving because I'm bored, the issue is due to a call to I18n on a dedicated server, the call occurs here: https://github.com/elytra/Correlated/blob/1.11.2/src/main/java/com/elytradev/correlated/item/ItemMisc.java#L145

Why this is causing a crash is beyond me because Minecraft does the same call in the super method...

**Comment by falkreon** [comment] 2017-04-22 17:29
This looks like one of the coremods present... and there are a LOT of coremods present. Correlated doesn't call getItemStackDisplayName on the server, and if someone's doing that they'll crash any item, not just Correlated's.

Whoever it is, look for StatList modifications. I think that's where the faulty ASM is.

**Comment by unascribed** [comment] 2017-04-22 17:50
Duplicate of #58

**Closed by unascribed** 2017-04-22 17:50 UTC
Labels: k: Not Our Bug, n: Breaks Servers

**Comment by unascribed** [comment] 2017-04-24 00:41
Fix released as [v2.0.0a5](https://github.com/elytra/Correlated/releases/tag/1.11.2-2.0.0a5).
